name: rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rubocop
      uses: gimenete/rubocop-action@1.0
    - name: Check rubocop
      run: bundle exec rubocop
