name: rubocop

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
      run: bundle exec rubocop
